spring.application.name=kappi_port
spring.datasource.url=jdbc:postgresql://localhost/portkappi
spring.datasource.username=postgres
spring.datasource.password=qwedsazxc
spring.jpa.generate-ddl=true
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB

spring.mustache.servlet.expose-request-attributes=true